version: "3.8"

services:
  relayai:
    image: vickystardust5/relayai:latest
    container_name: relayai
    ports:
      - "3000:3000"
    environment:
      - AMQP_HOST=rabbitmq
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
      - ollama

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitMQ

  ollama:
    image: ollama/ollama:latest
    container_name: relayai_inference
    environment:
      - OLLAMA_NUM_PARALLEL=2
    volumes:
      - ollama_storage:/root/.ollama

volumes:
  ollama_storage:
